### ISSUE TITLE
[FEATURE] Add link to CHANGELOG in Release

### ISSUE THREAD

**Issue by n-rodriguez** [epistrephein/rubies#82]
## Feature description
Hi there! It could be nice to have a link to a CHANGELOG file in https://github.com/epistrephein/rubies#releases

## Possible implementations
If possible, suggest a way to add this feature.

## Alternatives considered
A description of any alternative solutions or features you've considered.

## Additional context
Add any other context about the feature here.

**Comment by epistrephein** [comment]
Yeah, that's definitely missing. 😄 
Basically, after the v2.0 rewrite, the releases were just a way to pack changes in a tag and deploy just that (and nothing really changed in the API interface since 2.0).
But I guess it still makes sense to have a CHANGELOG, even if just for history.

I'll start one and try to backfill all previous versions down to 2.0. Thanks! 💛
